spring:
  application:
    name: provider
  datasource:
    url: jdbc:mysql://localhost:3306/tvmall?useUnicode=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://172.16.8.125:8081/eureka
mybatis:
  type-aliases-package: cn.yunhe.java.pojo
info:
  application-name: 这个是电视商城提供者
management:
 security:
 #关闭安全验证，否则访问refresh端点时会提示权限不足
 enabled: false
